# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uP9uI745hFA-lOqhAXEslffu2GhKvA9Q
"""

!pip install -q -U google-generativeai

import google.generativeai as i_generativo

from google.colab import userdata

GOOGLE_GEMINI_API_KEY = userdata.get("GOOGLE_GEMINI_API_KEY")

i_generativo.configure(api_key=GOOGLE_GEMINI_API_KEY)

for m in i_generativo.list_models ():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

model = i_generativo.GenerativeModel("gemini-1.5-pro-latest")

response = model.generate_content("Quem criou os modelos de IA Gemini?")
response.text

chat = model.start_chat(history=[])

prompt = input("Olá! Eu sou o Arnold, qual sua pergunta:")

while prompt != "fim":
  response = chat.send_message(prompt)
  print(response.text)
  prompt = input("Olá! Eu sou o Arnold, qual sua pergunta:")